username = "<Your codegrade username>"
password = "<Your codegrade password>"
tenant = "<Your codegrade tenant>"
assignment_id = <The Codegrade ID for the assignment you'd like to run>
basepath = "<The directory you'd like to download the assignments to>"
artifacts_repo = "<A github repo with artifacts that will be used to setup the compilation pipeline>"
setup_commands = [<Any commands needed to setup the compilation environment>]
compile_commands = [<Commands needed to compile the assignments>]
submission_template = "<Template file that must be provided as part of artifacts. This will be used to generate a slurm submission script>"
leaderboard_repo = "<github repo that the leaderboard must be pushed to>"
auto_update = True
update_frequency = <number of hours in which autoupdate should be done>